services:
  ctx:
    image: alpine
    volumes:
      - .:/app
    command: /app/init.sh

  db:
    depends_on:
      ctx:
        condition: service_completed_successfully
    build:
      context: database
      dockerfile: postgres.dockerfile
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - "./database/data:/var/lib/postgresql/data:Z"

  pgadmin:
    depends_on:
      db:
        condition: service_healthy
      ctx:
        condition: service_completed_successfully
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
    user: root
    volumes:
      - "./database/pgadmin_data:/var/lib/pgadmin:Z"
    ports:
      - "8420:80"

  app:
    build: .
    depends_on:
      db:
        condition: service_healthy
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              device_ids: ['0']
              capabilities: [gpu]
